feat: debugs updated

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -95,21 +95,29 @@ jobs:
                   echo "Publishing crate $crate..."
 
                   crate_name=${crate##*/}
-
-                  # local_version=$(cargo info ${crate_name} | grep "version" | grep --invert-match "rust-version")
-                  # local_version=${local_version% (*}
-                  # local_version=${local_version#version: }
-                  local_version=$(cargo info ${crate_name} | grep "version" | grep --invert-match "rust-version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-
-                  # remote_version=$(cargo search --limit 1 --quiet ${crate_name} | grep --before-context=0 --after-context=0 ${crate_name})
-                  # remote_version=${remote_version%\"*#*}
-                  # remote_version=${remote_version##${crate_name} = \"}
-                  remote_version=$(cargo search --limit 1 --quiet ${crate_name} | grep --before-context=0 --after-context=0 ${crate_name} | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-
                   if [[ "${debug}" == "true" ]]
                   then
                       echo "crate_name=${crate_name}"
+                  fi
+
+
+                  if [[ "${debug}" == "true" ]]
+                  then
+                      cargo info ${crate_name} | grep "version" | grep --invert-match "rust-version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "Cannot fetch remote version"
+                  fi
+                  local_version=$(cargo info ${crate_name} | grep "version" | grep --invert-match "rust-version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+                  if [[ "${debug}" == "true" ]]
+                  then
                       echo local_version=${local_version}
+                  fi
+
+                  if [[ "${debug}" == "true" ]]
+                  then
+                      cargo search --limit 1 --quiet ${crate_name} | grep --before-context=0 --after-context=0 ${crate_name} | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo "Cannot fetch remote version"
+                  fi
+                  remote_version=$(cargo search --limit 1 --quiet ${crate_name} | grep --before-context=0 --after-context=0 ${crate_name} | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+                  if [[ "${debug}" == "true" ]]
+                  then
                       echo remote_version=${remote_version}
                   fi
 
